# Preparing Data for Drug Interactions LLM #

In [ ]:
import pandas as pd
import os
import numpy as np

In [2]:
pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", None)

In [ ]:
# mount to drive
from google.colab import drive
drive.mount('/content/drive')
#  %cd /content/drive/MyDrive/Duke-MIDS/Intelligent-Agents/Intelligent-Agents-Project/code

In [ ]:
PROJECT_FOLDER_NAME = "Intelligent-Agents-Project"
REQ_REL_PATH = "requirements.txt"

# def find_project_root(folder_name: str, search_root="/content/drive") -> str:
#     for base in ["MyDrive", "Shareddrives"]:
#         start = os.path.join(search_root, base)
#         if not os.path.isdir(start):
#             continue
#         for root, dirs, files in os.walk(start):
#             if os.path.basename(root) == folder_name:
#                 return root
#     raise FileNotFoundError(f"Could not find folder named '{folder_name}' under Drive.")


# below line will take a few seconds to run because its searching for the local file path, or just specify it yourself by setting project_root var below
# project_root = find_project_root(PROJECT_FOLDER_NAME)
# or hardcode /content/drive/MyDrive/Duke-MIDS/Intelligent-Agents/Intelligent-Agents-Project
project_root = '/content/drive/MyDrive/Intelligent-Agents-Project'


project_root = project_root + '/code'
requirements_path = os.path.join(project_root, REQ_REL_PATH)

print("Project root:", project_root)
print("Requirements:", requirements_path)
!pip -q install -r "$requirements_path"

Project root: /content/drive/MyDrive/Intelligent-Agents-Project/code
Requirements: /content/drive/MyDrive/Intelligent-Agents-Project/code/requirements.txt

## Load Data ##

In [ ]:
# store dictionary with each dataset and the interaction it involves
# we have datasets A, B, D, H, L, P, R, V

dataset_by_interactions = {
    'A': 'Interaction involving alimentary tract and metabolism drugs',
    'B': 'Interaction involving blood and blood forming organs drugs',
    'D': 'Interaction involving dermatologicals drugs',
    'H': 'Interaction involving systemic hormonal preparations, excluding sex hormones and insulins drugs',
    'L': 'Interaction involving antineoplastic and immunomodulating agents drugs',
    'P': 'Interaction involving antiparasitic products, insecticides and repellents drugs',
    'R': 'Interaction involving respiratory system drugs',
    'V': 'Interaction involving various drugs'
}

In [ ]:


data_folder = os.path.join(project_root, "data")

# dictionary to store dataframes
dataframes = {}

for file_name in os.listdir(data_folder):
    if file_name.endswith(".csv"):
        file_path = os.path.join(data_folder, file_name)
        df_name = os.path.splitext(file_name)[0]
        dataframes[df_name] = pd.read_csv(file_path)
        print(f"Loaded {file_name} into dataframe '{df_name}'")


        df_name = os.path.splitext(file_name)[0]
        df_letter = df_name[-1]

        dataframes[df_name]['Dataset'] = df_letter
        dataframes[df_name]['Category'] = dataset_by_interactions[df_letter]

# make sure all the columns in each dataframe are the same
for df in dataframes.values():
    assert all(df.columns == dataframes[next(iter(dataframes))].columns)
    print(df.columns)

Loaded ddinter_downloads_code_A.csv into dataframe 'ddinter_downloads_code_A'
Loaded ddinter_downloads_code_P.csv into dataframe 'ddinter_downloads_code_P'
Loaded ddinter_downloads_code_B.csv into dataframe 'ddinter_downloads_code_B'
Loaded ddinter_downloads_code_H.csv into dataframe 'ddinter_downloads_code_H'
Loaded ddinter_downloads_code_D.csv into dataframe 'ddinter_downloads_code_D'
Loaded ddinter_downloads_code_R.csv into dataframe 'ddinter_downloads_code_R'
Loaded ddinter_downloads_code_V.csv into dataframe 'ddinter_downloads_code_V'
Loaded ddinter_downloads_code_L.csv into dataframe 'ddinter_downloads_code_L'
Index(['DDInterID_A', 'Drug_A', 'DDInterID_B', 'Drug_B', 'Level', 'Dataset',
       'Category'],
      dtype='object')
Index(['DDInterID_A', 'Drug_A', 'DDInterID_B', 'Drug_B', 'Level', 'Dataset',
       'Category'],
      dtype='object')
Index(['DDInterID_A', 'Drug_A', 'DDInterID_B', 'Drug_B', 'Level', 'Dataset',
       'Category'],
      dtype='object')
Index(['DDInterID_A', 'Drug_A', 'DDInterID_B', 'Drug_B', 'Level', 'Dataset',
       'Category'],
      dtype='object')
Index(['DDInterID_A', 'Drug_A', 'DDInterID_B', 'Drug_B', 'Level', 'Dataset',
       'Category'],
      dtype='object')
Index(['DDInterID_A', 'Drug_A', 'DDInterID_B', 'Drug_B', 'Level', 'Dataset',
       'Category'],
      dtype='object')
Index(['DDInterID_A', 'Drug_A', 'DDInterID_B', 'Drug_B', 'Level', 'Dataset',
       'Category'],
      dtype='object')
Index(['DDInterID_A', 'Drug_A', 'DDInterID_B', 'Drug_B', 'Level', 'Dataset',
       'Category'],
      dtype='object')

In [ ]:
# look at first dataset to make sure its loaded correctly
dataframes['ddinter_downloads_code_A'].head()

,DDInterID_A,Drug_A,DDInterID_B,Drug_B,Level,Dataset,Category
0,DDInter1263,Naltrexone,DDInter1,Abacavir,Moderate,A,Interaction involving alimentary tract and metabolism drugs
1,DDInter1,Abacavir,DDInter1348,Orlistat,Moderate,A,Interaction involving alimentary tract and metabolism drugs
2,DDInter58,Aluminum hydroxide,DDInter582,Dolutegravir,Major,A,Interaction involving alimentary tract and metabolism drugs
3,DDInter112,Aprepitant,DDInter582,Dolutegravir,Minor,A,Interaction involving alimentary tract and metabolism drugs
4,DDInter138,Attapulgite,DDInter582,Dolutegravir,Major,A,Interaction involving alimentary tract and metabolism drugs

In [ ]:
# create a df and combine all of them
df = pd.concat(dataframes.values(), ignore_index=True)
df

,DDInterID_A,Drug_A,DDInterID_B,Drug_B,Level,Dataset,Category
0,DDInter1263,Naltrexone,DDInter1,Abacavir,Moderate,A,Interaction involving alimentary tract and metabolism drugs
1,DDInter1,Abacavir,DDInter1348,Orlistat,Moderate,A,Interaction involving alimentary tract and metabolism drugs
2,DDInter58,Aluminum hydroxide,DDInter582,Dolutegravir,Major,A,Interaction involving alimentary tract and metabolism drugs
3,DDInter112,Aprepitant,DDInter582,Dolutegravir,Minor,A,Interaction involving alimentary tract and metabolism drugs
4,DDInter138,Attapulgite,DDInter582,Dolutegravir,Major,A,Interaction involving alimentary tract and metabolism drugs
...,...,...,...,...,...,...,...
222378,DDInter667,Erlotinib,DDInter766,Fluticasone,Unknown,L,Interaction involving antineoplastic and immunomodulating agents drugs
222379,DDInter789,Fulvestrant,DDInter766,Fluticasone,Unknown,L,Interaction involving antineoplastic and immunomodulating agents drugs
222380,DDInter1156,Mercaptopurine,DDInter766,Fluticasone,Unknown,L,Interaction involving antineoplastic and immunomodulating agents drugs
222381,DDInter810,Gefitinib,DDInter888,Hydrocortisone butyrate,Unknown,L,Interaction involving antineoplastic and immunomodulating agents drugs
222382,DDInter1735,Tacrolimus,DDInter888,Hydrocortisone butyrate,Unknown,L,Interaction involving antineoplastic and immunomodulating agents drugs

In [ ]:

np.unique(df['Level']), np.unique(df['Category'])

(array(['Major', 'Minor', 'Moderate', 'Unknown'], dtype=object),
 array(['Interaction involving alimentary tract and metabolism drugs',
        'Interaction involving antineoplastic and immunomodulating agents drugs',
        'Interaction involving antiparasitic products, insecticides and repellents drugs',
        'Interaction involving blood and blood forming organs drugs',
        'Interaction involving dermatologicals drugs',
        'Interaction involving respiratory system drugs',
        'Interaction involving systemic hormonal preparations, excluding sex hormones and insulins drugs',
        'Interaction involving various drugs'], dtype=object))

### Flexibility in Designing Training Question/Answers

In [ ]:
# hardcode severity explanations, so it'll include one of these in the answer based on the Interaction Level value
severity_explanations = {
    "Major": "This combination may lead to serious clinical consequences and should generally be avoided or used only with close medical supervision.",
    "Moderate": "This combination may require dose adjustments or additional monitoring to ensure patient safety.",
    "Minor": "This interaction is usually mild but should still be considered in the overall treatment plan.",
    "Unknown": "There is limited or insufficient evidence about the clinical significance of this interaction."
}




def make_qa(row):
    drug_a = row["Drug_A"]
    drug_b = row["Drug_B"]
    level  = row["Level"]
    cat    = row["Category"]

    question = f"How do {drug_a} and {drug_b} interact?"

    # this is where we can change how we format the answer
    explanation = severity_explanations.get(level, "")

    answer = (
        f"{drug_a} and {drug_b} are reported to have a {level.lower()} interaction. "
        f"This interaction is classified under {cat.lower()}. "
        f"{explanation}"
    )

    # answer = (
    #     f"When taken together, {drug_a} and {drug_b} may result in a {level.lower()} interaction. "
    #     f"This type of interaction is related to {cat.lower()}. "
    #     f"{explanation}"
    # )
    return question, answer


data = df.copy()
data[["question", "answer"]] = data.apply(lambda r: pd.Series(make_qa(r)), axis=1)


"""
should we add variation in the question formats for finetuning?
Because you're fine-tuning for general questions like:

"Can I take X and Y together?"

You should add variation in question phrasing.

Otherwise your model will overfit to only:

"How do X and Y interact?"
"""

'\nshould we add variation in the question formats for finetuning?\nBecause you\'re fine-tuning for general questions like:\n\n"Can I take X and Y together?"\n\nYou should add variation in question phrasing.\n\nOtherwise your model will overfit to only:\n\n"How do X and Y interact?"\n'

In [ ]:
# look at random 10 from data
data.sample(10)

,DDInterID_A,Drug_A,DDInterID_B,Drug_B,Level,Dataset,Category,question,answer
172577,DDInter602,Dronedarone,DDInter259,Cabazitaxel,Moderate,L,Interaction involving antineoplastic and immunomodulating agents drugs,How do Dronedarone and Cabazitaxel interact?,Dronedarone and Cabazitaxel are reported to have a moderate interaction. This interaction is classified under interaction involving antineoplastic and immunomodulating agents drugs. This combination may require dose adjustments or additional monitoring to ensure patient safety.
107893,DDInter1066,Lidocaine,DDInter1166,Methadone,Unknown,D,Interaction involving dermatologicals drugs,How do Lidocaine and Methadone interact?,Lidocaine and Methadone are reported to have a unknown interaction. This interaction is classified under interaction involving dermatologicals drugs. There is limited or insufficient evidence about the clinical significance of this interaction.
26940,DDInter1176,Methoxamine,DDInter931,Insulin detemir,Moderate,A,Interaction involving alimentary tract and metabolism drugs,How do Methoxamine and Insulin detemir interact?,Methoxamine and Insulin detemir are reported to have a moderate interaction. This interaction is classified under interaction involving alimentary tract and metabolism drugs. This combination may require dose adjustments or additional monitoring to ensure patient safety.
59878,DDInter1557,Quinine,DDInter1293,Nilotinib,Major,P,"Interaction involving antiparasitic products, insecticides and repellents drugs",How do Quinine and Nilotinib interact?,"Quinine and Nilotinib are reported to have a major interaction. This interaction is classified under interaction involving antiparasitic products, insecticides and repellents drugs. This combination may lead to serious clinical consequences and should generally be avoided or used only with close medical supervision."
189277,DDInter840,Granisetron,DDInter1880,Triptorelin,Moderate,L,Interaction involving antineoplastic and immunomodulating agents drugs,How do Granisetron and Triptorelin interact?,Granisetron and Triptorelin are reported to have a moderate interaction. This interaction is classified under interaction involving antineoplastic and immunomodulating agents drugs. This combination may require dose adjustments or additional monitoring to ensure patient safety.
108038,DDInter1066,Lidocaine,DDInter1377,Paclitaxel,Unknown,D,Interaction involving dermatologicals drugs,How do Lidocaine and Paclitaxel interact?,Lidocaine and Paclitaxel are reported to have a unknown interaction. This interaction is classified under interaction involving dermatologicals drugs. There is limited or insufficient evidence about the clinical significance of this interaction.
69624,DDInter117,Argatroban,DDInter1335,Omacetaxine mepesuccinate,Major,B,Interaction involving blood and blood forming organs drugs,How do Argatroban and Omacetaxine mepesuccinate interact?,Argatroban and Omacetaxine mepesuccinate are reported to have a major interaction. This interaction is classified under interaction involving blood and blood forming organs drugs. This combination may lead to serious clinical consequences and should generally be avoided or used only with close medical supervision.
9020,DDInter136,Atropine,DDInter1155,Mepyramine,Moderate,A,Interaction involving alimentary tract and metabolism drugs,How do Atropine and Mepyramine interact?,Atropine and Mepyramine are reported to have a moderate interaction. This interaction is classified under interaction involving alimentary tract and metabolism drugs. This combination may require dose adjustments or additional monitoring to ensure patient safety.
12327,DDInter247,Budesonide (nasal),DDInter602,Dronedarone,Moderate,A,Interaction involving alimentary tract and metabolism drugs,How do Budesonide (nasal) and Dronedarone interact?,Budesonide (nasal) and Dronedarone are reported to have a moderate interaction. This interaction is classified under interaction involving alimentary tract and metabolism drugs. This combination may require dose adjustments or additional monitoring to ensure patient safety.
1592,DDInter1342,Ondansetron,DDInter776,Formoterol,Moderate,A,Interaction involving alimentary tract and metabolism drugs,How do Ondansetron and Formoterol interact?,Ondansetron and Formoterol are reported to have a moderate interaction. This interaction is classified under interaction involving alimentary tract and metabolism drugs. This combination may require dose adjustments or additional monitoring to ensure patient safety.

In [ ]:
data.shape

(222383, 9)